
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 19 2024 14:56:45 IST (Jun 19 2024 09:26:45 UTC)

// Verification Directory fv/vedic8bit 

module hag_191(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__2398(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_140(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g66__5107(.A (b), .B (cin), .CI (a), .S (s), .CO (c));
endmodule

module fag_139(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__6260(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_138(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__4319(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_137(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__8428(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_136(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__5526(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_135(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__6783(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_134(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__3680(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module rca8bit(s, cout, a, b);
  input [7:0] a, b;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire [7:0] s;
  wire cout;
  wire [7:1] w;
  hag_191 x1(s[0], w[1], a[0], b[0]);
  fag_140 x2(s[1], w[2], a[1], b[1], w[1]);
  fag_139 x3(s[2], w[3], a[2], b[2], w[2]);
  fag_138 x4(s[3], w[4], a[3], b[3], w[3]);
  fag_137 x5(s[4], w[5], a[4], b[4], w[4]);
  fag_136 x6(s[5], w[6], a[5], b[5], w[5]);
  fag_135 x7(s[6], w[7], a[6], b[6], w[6]);
  fag_134 x8(s[7], cout, a[7], b[7], w[7]);
endmodule

module hag_178(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__1617(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_133(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__2802(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_132(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__1705(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_131(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__5122(.A (a), .B (b), .CI (cin), .S (s), .CO (c));
endmodule

module fag_42(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__8246(.A (b), .B (cin), .S (s), .CO (c));
endmodule

module fag_42_174(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__7098(.A (b), .B (cin), .S (s), .CO (c));
endmodule

module fag_42_173(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__6131(.A (b), .B (cin), .S (s), .CO (c));
endmodule

module fag_42_172(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  XOR2X1 g13__1881(.A (cin), .B (b), .Y (s));
endmodule

module rca8bit_1(s, cout, a, b);
  input [7:0] a, b;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire [7:0] s;
  wire cout;
  wire [7:1] w;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2, n_1;
  hag_178 x1(.s (s[0]), .c (w[1]), .a (a[0]), .b (b[0]));
  fag_133 x2(.s (s[1]), .c (w[2]), .a (a[1]), .b (b[1]), .cin (w[1]));
  fag_132 x3(.s (s[2]), .c (w[3]), .a (a[2]), .b (b[2]), .cin (w[2]));
  fag_131 x4(.s (s[3]), .c (w[4]), .a (a[3]), .b (b[3]), .cin (w[3]));
  fag_42 x5(.s (s[4]), .c (w[5]), .a (UNCONNECTED_HIER_Z), .b (b[4]),
       .cin (w[4]));
  fag_42_174 x6(.s (s[5]), .c (w[6]), .a (UNCONNECTED_HIER_Z0), .b
       (b[5]), .cin (w[5]));
  fag_42_173 x7(.s (s[6]), .c (w[7]), .a (UNCONNECTED_HIER_Z1), .b
       (b[6]), .cin (w[6]));
  fag_42_172 x8(.s (s[7]), .c (n_1), .a (UNCONNECTED_HIER_Z2), .b
       (b[7]), .cin (w[7]));
endmodule

module hag_177(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__5115(.A (a), .B (b), .S (s), .CO (c));
endmodule

module fag_130(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__7482(.A (cin), .B (a), .CI (b), .S (s), .CO (c));
endmodule

module fag_129(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__4733(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_128(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__6161(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_127(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__9315(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module fag_52_175(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__9945(.A (a), .B (cin), .S (s), .CO (c));
endmodule

module fag_52_176(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDHXL g24__2883(.A (a), .B (cin), .S (s), .CO (c));
endmodule

module fag_52(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  XOR2X1 g17__19(.A (cin), .B (a), .Y (s));
endmodule

module rca8bit_2(s, cout, a, b);
  input [7:0] a, b;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire [7:0] s;
  wire cout;
  wire [7:1] w;
  wire UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5,
       n_1;
  hag_177 x1(.s (s[0]), .c (w[1]), .a (a[0]), .b (b[0]));
  fag_130 x2(.s (s[1]), .c (w[2]), .a (a[1]), .b (b[1]), .cin (w[1]));
  fag_129 x3(.s (s[2]), .c (w[3]), .a (a[2]), .b (b[2]), .cin (w[2]));
  fag_128 x4(.s (s[3]), .c (w[4]), .a (a[3]), .b (b[3]), .cin (w[3]));
  fag_127 x5(.s (s[4]), .c (w[5]), .a (a[4]), .b (b[4]), .cin (w[4]));
  fag_52_175 x6(.s (s[5]), .c (w[6]), .a (a[5]), .b
       (UNCONNECTED_HIER_Z3), .cin (w[5]));
  fag_52_176 x7(.s (s[6]), .c (w[7]), .a (a[6]), .b
       (UNCONNECTED_HIER_Z4), .cin (w[6]));
  fag_52 x8(.s (s[7]), .c (n_1), .a (a[7]), .b (UNCONNECTED_HIER_Z5),
       .cin (w[7]));
endmodule

module andg(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__1666(.A (a), .B (b), .Y (y));
endmodule

module andg_126(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__7410(.A (a), .B (b), .Y (y));
endmodule

module andg_125(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__6417(.A (a), .B (b), .Y (y));
endmodule

module hag(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__5477(.A (a), .B (b), .S (s), .CO (c));
endmodule

module andg_124(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__2398(.A (a), .B (b), .Y (y));
endmodule

module andg_123(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__5107(.A (a), .B (b), .Y (y));
endmodule

module andg_122(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__6260(.A (a), .B (b), .Y (y));
endmodule

module fag(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  wire n_5, n_12;
  OAI2BB1X1 g66__4319(.A0N (b), .A1N (a), .B0 (n_5), .Y (c));
  OAI21XL g68__5526(.A0 (a), .A1 (b), .B0 (cin), .Y (n_5));
  XOR2X1 g2(.A (cin), .B (n_12), .Y (s));
  XOR2X1 g97(.A (a), .B (b), .Y (n_12));
endmodule

module hag_194(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  AOI2BB1XL g24__3680(.A0N (b), .A1N (a), .B0 (c), .Y (s));
  AND2X2 g25__1617(.A (b), .B (a), .Y (c));
endmodule

module andg_121(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__2802(.A (a), .B (b), .Y (y));
endmodule

module andg_120(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__1705(.A (a), .B (b), .Y (y));
endmodule

module andg_119(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__5122(.A (a), .B (b), .Y (y));
endmodule

module fag_165(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__8246(.A (a), .B (cin), .CI (b), .S (s), .CO (c));
endmodule

module andg_118(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__7098(.A (a), .B (b), .Y (y));
endmodule

module hag_193(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__6131(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_161(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__1881(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_117(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__5115(.A (a), .B (b), .Y (y));
endmodule

module andg_116(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__7482(.A (a), .B (b), .Y (y));
endmodule

module andg_115(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g2__4733(.A (a), .B (b), .Y (y));
endmodule

module fag_157(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__6161(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_192(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__9315(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_153(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__9945(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_114(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2883(.A (a), .B (b), .Y (y));
endmodule

module andg_113(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2346(.A (a), .B (b), .Y (y));
endmodule

module fag_149(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__1666(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_145(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__7410(.A (b), .B (cin), .CI (a), .S (s), .CO (c));
endmodule

module andg_112(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6417(.A (a), .B (b), .Y (y));
endmodule

module fag_141(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__5477(.A (b), .B (cin), .CI (a), .S (s), .CO (c));
endmodule

module vedic4bit(p, a, b);
  input [3:0] a, b;
  output [7:0] p;
  wire [3:0] a, b;
  wire [7:0] p;
  wire [32:1] w;
  andg z1(p[0], a[0], b[0]);
  andg_126 z2(w[1], a[1], b[0]);
  andg_125 z3(w[2], a[0], b[1]);
  hag z4(p[1], w[3], w[1], w[2]);
  andg_124 z5(w[4], a[2], b[0]);
  andg_123 z6(w[5], a[1], b[1]);
  andg_122 z7(w[6], a[0], b[2]);
  fag z8(w[7], w[8], w[4], w[5], w[6]);
  hag_194 z9(p[2], w[9], w[3], w[7]);
  andg_121 z10(w[10], a[3], b[0]);
  andg_120 z11(w[11], a[2], b[1]);
  andg_119 z12(w[12], a[1], b[2]);
  fag_165 z13(w[13], w[14], w[10], w[11], w[12]);
  andg_118 z14(w[15], a[0], b[3]);
  hag_193 z15(w[16], w[17], w[13], w[15]);
  fag_161 z16(p[3], w[18], w[16], w[8], w[9]);
  andg_117 z17(w[19], a[3], b[1]);
  andg_116 z19(w[20], a[2], b[2]);
  andg_115 z20(w[21], a[1], b[3]);
  fag_157 z21(w[22], w[23], w[20], w[21], w[19]);
  hag_192 z22(w[24], w[25], w[22], w[14]);
  fag_153 z23(p[4], w[26], w[18], w[17], w[24]);
  andg_114 z24(w[27], a[2], b[3]);
  andg_113 z25(w[28], a[3], b[2]);
  fag_149 z26(w[29], w[30], w[23], w[27], w[28]);
  fag_145 z27(p[5], w[31], w[26], w[25], w[29]);
  andg_112 z28(w[32], a[3], b[3]);
  fag_141 z29(p[6], p[7], w[31], w[30], w[32]);
endmodule

module andg_111(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2398(.A (a), .B (b), .Y (y));
endmodule

module andg_110(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5107(.A (a), .B (b), .Y (y));
endmodule

module andg_109(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6260(.A (a), .B (b), .Y (y));
endmodule

module hag_190(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__4319(.A (a), .B (b), .S (s), .CO (c));
endmodule

module andg_108(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__8428(.A (a), .B (b), .Y (y));
endmodule

module andg_107(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5526(.A (a), .B (b), .Y (y));
endmodule

module andg_106(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6783(.A (a), .B (b), .Y (y));
endmodule

module fag_171(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__3680(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_189(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__1617(.A (a), .B (b), .S (s), .CO (c));
endmodule

module andg_105(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2802(.A (a), .B (b), .Y (y));
endmodule

module andg_104(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__1705(.A (a), .B (b), .Y (y));
endmodule

module andg_103(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5122(.A (a), .B (b), .Y (y));
endmodule

module fag_168(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__8246(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module andg_102(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__7098(.A (a), .B (b), .Y (y));
endmodule

module hag_188(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__6131(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_164(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__1881(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_101(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5115(.A (a), .B (b), .Y (y));
endmodule

module andg_100(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__7482(.A (a), .B (b), .Y (y));
endmodule

module andg_99(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__4733(.A (a), .B (b), .Y (y));
endmodule

module fag_160(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__6161(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_187(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__9315(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_156(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__9945(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_98(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2883(.A (a), .B (b), .Y (y));
endmodule

module andg_97(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2346(.A (a), .B (b), .Y (y));
endmodule

module fag_152(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__1666(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_148(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__7410(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_96(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6417(.A (a), .B (b), .Y (y));
endmodule

module fag_144(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__5477(.A (b), .B (cin), .CI (a), .S (s), .CO (c));
endmodule

module vedic4bit_197(p, a, b);
  input [3:0] a, b;
  output [7:0] p;
  wire [3:0] a, b;
  wire [7:0] p;
  wire [32:1] w;
  andg_111 z1(.y (p[0]), .a (a[0]), .b (b[0]));
  andg_110 z2(.y (w[1]), .a (a[1]), .b (b[0]));
  andg_109 z3(.y (w[2]), .a (a[0]), .b (b[1]));
  hag_190 z4(.s (p[1]), .c (w[3]), .a (w[1]), .b (w[2]));
  andg_108 z5(.y (w[4]), .a (a[2]), .b (b[0]));
  andg_107 z6(.y (w[5]), .a (a[1]), .b (b[1]));
  andg_106 z7(.y (w[6]), .a (a[0]), .b (b[2]));
  fag_171 z8(.s (w[7]), .c (w[8]), .a (w[4]), .b (w[5]), .cin (w[6]));
  hag_189 z9(.s (p[2]), .c (w[9]), .a (w[3]), .b (w[7]));
  andg_105 z10(.y (w[10]), .a (a[3]), .b (b[0]));
  andg_104 z11(.y (w[11]), .a (a[2]), .b (b[1]));
  andg_103 z12(.y (w[12]), .a (a[1]), .b (b[2]));
  fag_168 z13(.s (w[13]), .c (w[14]), .a (w[10]), .b (w[11]), .cin
       (w[12]));
  andg_102 z14(.y (w[15]), .a (a[0]), .b (b[3]));
  hag_188 z15(.s (w[16]), .c (w[17]), .a (w[13]), .b (w[15]));
  fag_164 z16(.s (p[3]), .c (w[18]), .a (w[16]), .b (w[8]), .cin
       (w[9]));
  andg_101 z17(.y (w[19]), .a (a[3]), .b (b[1]));
  andg_100 z19(.y (w[20]), .a (a[2]), .b (b[2]));
  andg_99 z20(.y (w[21]), .a (a[1]), .b (b[3]));
  fag_160 z21(.s (w[22]), .c (w[23]), .a (w[20]), .b (w[21]), .cin
       (w[19]));
  hag_187 z22(.s (w[24]), .c (w[25]), .a (w[22]), .b (w[14]));
  fag_156 z23(.s (p[4]), .c (w[26]), .a (w[18]), .b (w[17]), .cin
       (w[24]));
  andg_98 z24(.y (w[27]), .a (a[2]), .b (b[3]));
  andg_97 z25(.y (w[28]), .a (a[3]), .b (b[2]));
  fag_152 z26(.s (w[29]), .c (w[30]), .a (w[23]), .b (w[27]), .cin
       (w[28]));
  fag_148 z27(.s (p[5]), .c (w[31]), .a (w[26]), .b (w[25]), .cin
       (w[29]));
  andg_96 z28(.y (w[32]), .a (a[3]), .b (b[3]));
  fag_144 z29(.s (p[6]), .c (p[7]), .a (w[31]), .b (w[30]), .cin
       (w[32]));
endmodule

module andg_95(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2398(.A (a), .B (b), .Y (y));
endmodule

module andg_94(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5107(.A (a), .B (b), .Y (y));
endmodule

module andg_93(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6260(.A (a), .B (b), .Y (y));
endmodule

module hag_186(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__4319(.A (a), .B (b), .S (s), .CO (c));
endmodule

module andg_92(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__8428(.A (a), .B (b), .Y (y));
endmodule

module andg_91(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5526(.A (a), .B (b), .Y (y));
endmodule

module andg_90(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6783(.A (a), .B (b), .Y (y));
endmodule

module fag_170(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__3680(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_185(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__1617(.A (a), .B (b), .S (s), .CO (c));
endmodule

module andg_89(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2802(.A (a), .B (b), .Y (y));
endmodule

module andg_88(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__1705(.A (a), .B (b), .Y (y));
endmodule

module andg_87(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5122(.A (a), .B (b), .Y (y));
endmodule

module fag_167(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__8246(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module andg_86(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__7098(.A (a), .B (b), .Y (y));
endmodule

module hag_184(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__6131(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_163(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__1881(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_85(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5115(.A (a), .B (b), .Y (y));
endmodule

module andg_84(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__7482(.A (a), .B (b), .Y (y));
endmodule

module andg_83(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__4733(.A (a), .B (b), .Y (y));
endmodule

module fag_159(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__6161(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_183(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__9315(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_155(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__9945(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_82(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2883(.A (a), .B (b), .Y (y));
endmodule

module andg_81(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2346(.A (a), .B (b), .Y (y));
endmodule

module fag_151(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__1666(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_147(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__7410(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_80(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6417(.A (a), .B (b), .Y (y));
endmodule

module fag_143(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__5477(.A (b), .B (cin), .CI (a), .S (s), .CO (c));
endmodule

module vedic4bit_196(p, a, b);
  input [3:0] a, b;
  output [7:0] p;
  wire [3:0] a, b;
  wire [7:0] p;
  wire [32:1] w;
  andg_95 z1(.y (p[0]), .a (a[0]), .b (b[0]));
  andg_94 z2(.y (w[1]), .a (a[1]), .b (b[0]));
  andg_93 z3(.y (w[2]), .a (a[0]), .b (b[1]));
  hag_186 z4(.s (p[1]), .c (w[3]), .a (w[1]), .b (w[2]));
  andg_92 z5(.y (w[4]), .a (a[2]), .b (b[0]));
  andg_91 z6(.y (w[5]), .a (a[1]), .b (b[1]));
  andg_90 z7(.y (w[6]), .a (a[0]), .b (b[2]));
  fag_170 z8(.s (w[7]), .c (w[8]), .a (w[4]), .b (w[5]), .cin (w[6]));
  hag_185 z9(.s (p[2]), .c (w[9]), .a (w[3]), .b (w[7]));
  andg_89 z10(.y (w[10]), .a (a[3]), .b (b[0]));
  andg_88 z11(.y (w[11]), .a (a[2]), .b (b[1]));
  andg_87 z12(.y (w[12]), .a (a[1]), .b (b[2]));
  fag_167 z13(.s (w[13]), .c (w[14]), .a (w[10]), .b (w[11]), .cin
       (w[12]));
  andg_86 z14(.y (w[15]), .a (a[0]), .b (b[3]));
  hag_184 z15(.s (w[16]), .c (w[17]), .a (w[13]), .b (w[15]));
  fag_163 z16(.s (p[3]), .c (w[18]), .a (w[16]), .b (w[8]), .cin
       (w[9]));
  andg_85 z17(.y (w[19]), .a (a[3]), .b (b[1]));
  andg_84 z19(.y (w[20]), .a (a[2]), .b (b[2]));
  andg_83 z20(.y (w[21]), .a (a[1]), .b (b[3]));
  fag_159 z21(.s (w[22]), .c (w[23]), .a (w[20]), .b (w[21]), .cin
       (w[19]));
  hag_183 z22(.s (w[24]), .c (w[25]), .a (w[22]), .b (w[14]));
  fag_155 z23(.s (p[4]), .c (w[26]), .a (w[18]), .b (w[17]), .cin
       (w[24]));
  andg_82 z24(.y (w[27]), .a (a[2]), .b (b[3]));
  andg_81 z25(.y (w[28]), .a (a[3]), .b (b[2]));
  fag_151 z26(.s (w[29]), .c (w[30]), .a (w[23]), .b (w[27]), .cin
       (w[28]));
  fag_147 z27(.s (p[5]), .c (w[31]), .a (w[26]), .b (w[25]), .cin
       (w[29]));
  andg_80 z28(.y (w[32]), .a (a[3]), .b (b[3]));
  fag_143 z29(.s (p[6]), .c (p[7]), .a (w[31]), .b (w[30]), .cin
       (w[32]));
endmodule

module andg_79(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2398(.A (a), .B (b), .Y (y));
endmodule

module andg_78(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5107(.A (a), .B (b), .Y (y));
endmodule

module andg_77(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6260(.A (a), .B (b), .Y (y));
endmodule

module hag_182(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__4319(.A (a), .B (b), .S (s), .CO (c));
endmodule

module andg_76(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__8428(.A (a), .B (b), .Y (y));
endmodule

module andg_75(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5526(.A (a), .B (b), .Y (y));
endmodule

module andg_74(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6783(.A (a), .B (b), .Y (y));
endmodule

module fag_169(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__3680(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_181(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__1617(.A (a), .B (b), .S (s), .CO (c));
endmodule

module andg_73(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2802(.A (a), .B (b), .Y (y));
endmodule

module andg_72(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__1705(.A (a), .B (b), .Y (y));
endmodule

module andg_71(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5122(.A (a), .B (b), .Y (y));
endmodule

module fag_166(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__8246(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module andg_70(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__7098(.A (a), .B (b), .Y (y));
endmodule

module hag_180(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__6131(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_162(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__1881(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_69(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__5115(.A (a), .B (b), .Y (y));
endmodule

module andg_68(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__7482(.A (a), .B (b), .Y (y));
endmodule

module andg_67(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__4733(.A (a), .B (b), .Y (y));
endmodule

module fag_158(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__6161(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_179(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__9315(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_154(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__9945(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_66(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2883(.A (a), .B (b), .Y (y));
endmodule

module andg_65(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2346(.A (a), .B (b), .Y (y));
endmodule

module fag_150(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__1666(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_146(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g58__7410(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_64(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__6417(.A (a), .B (b), .Y (y));
endmodule

module fag_142(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX1 g66__5477(.A (b), .B (cin), .CI (a), .S (s), .CO (c));
endmodule

module vedic4bit_195(p, a, b);
  input [3:0] a, b;
  output [7:0] p;
  wire [3:0] a, b;
  wire [7:0] p;
  wire [32:1] w;
  andg_79 z1(.y (p[0]), .a (a[0]), .b (b[0]));
  andg_78 z2(.y (w[1]), .a (a[1]), .b (b[0]));
  andg_77 z3(.y (w[2]), .a (a[0]), .b (b[1]));
  hag_182 z4(.s (p[1]), .c (w[3]), .a (w[1]), .b (w[2]));
  andg_76 z5(.y (w[4]), .a (a[2]), .b (b[0]));
  andg_75 z6(.y (w[5]), .a (a[1]), .b (b[1]));
  andg_74 z7(.y (w[6]), .a (a[0]), .b (b[2]));
  fag_169 z8(.s (w[7]), .c (w[8]), .a (w[4]), .b (w[5]), .cin (w[6]));
  hag_181 z9(.s (p[2]), .c (w[9]), .a (w[3]), .b (w[7]));
  andg_73 z10(.y (w[10]), .a (a[3]), .b (b[0]));
  andg_72 z11(.y (w[11]), .a (a[2]), .b (b[1]));
  andg_71 z12(.y (w[12]), .a (a[1]), .b (b[2]));
  fag_166 z13(.s (w[13]), .c (w[14]), .a (w[10]), .b (w[11]), .cin
       (w[12]));
  andg_70 z14(.y (w[15]), .a (a[0]), .b (b[3]));
  hag_180 z15(.s (w[16]), .c (w[17]), .a (w[13]), .b (w[15]));
  fag_162 z16(.s (p[3]), .c (w[18]), .a (w[16]), .b (w[8]), .cin
       (w[9]));
  andg_69 z17(.y (w[19]), .a (a[3]), .b (b[1]));
  andg_68 z19(.y (w[20]), .a (a[2]), .b (b[2]));
  andg_67 z20(.y (w[21]), .a (a[1]), .b (b[3]));
  fag_158 z21(.s (w[22]), .c (w[23]), .a (w[20]), .b (w[21]), .cin
       (w[19]));
  hag_179 z22(.s (w[24]), .c (w[25]), .a (w[22]), .b (w[14]));
  fag_154 z23(.s (p[4]), .c (w[26]), .a (w[18]), .b (w[17]), .cin
       (w[24]));
  andg_66 z24(.y (w[27]), .a (a[2]), .b (b[3]));
  andg_65 z25(.y (w[28]), .a (a[3]), .b (b[2]));
  fag_150 z26(.s (w[29]), .c (w[30]), .a (w[23]), .b (w[27]), .cin
       (w[28]));
  fag_146 z27(.s (p[5]), .c (w[31]), .a (w[26]), .b (w[25]), .cin
       (w[29]));
  andg_64 z28(.y (w[32]), .a (a[3]), .b (b[3]));
  fag_142 z29(.s (p[6]), .c (p[7]), .a (w[31]), .b (w[30]), .cin
       (w[32]));
endmodule

module vedic8bit(p, a, b, clk);
  input [7:0] a, b;
  input clk;
  output [15:0] p;
  wire [7:0] a, b;
  wire clk;
  wire [15:0] p;
  wire [7:0] w1;
  wire [7:0] w2;
  wire [7:0] w4;
  wire [7:0] w;
  wire [7:0] w5;
  wire [7:0] w3;
  wire [7:0] w6;
  wire UNCONNECTED, UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10,
       UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z12;
  wire ca1, ca2, ca3;
  rca8bit n1(w4, ca1, w1, w2);
  rca8bit_1 n2(w5, ca2, {UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z8,
       UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z6, w[7:4]}, w4);
  rca8bit_2 n3(w6, ca3, w3, {UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z10, ca1, w5[7:4]});
  vedic4bit x1(w, a[3:0], b[3:0]);
  vedic4bit_197 x2(w1, a[3:0], b[7:4]);
  vedic4bit_196 x3(w2, a[7:4], b[3:0]);
  vedic4bit_195 x4(w3, a[7:4], b[7:4]);
  DFFX2 \p_reg[15] (.CK (clk), .D (w6[7]), .Q (p[15]), .QN
       (UNCONNECTED));
  DFFHQX2 \p_reg[14] (.CK (clk), .D (w6[6]), .Q (p[14]));
  DFFHQX2 \p_reg[13] (.CK (clk), .D (w6[5]), .Q (p[13]));
  DFFHQX2 \p_reg[12] (.CK (clk), .D (w6[4]), .Q (p[12]));
  DFFHQX2 \p_reg[11] (.CK (clk), .D (w6[3]), .Q (p[11]));
  DFFHQX2 \p_reg[10] (.CK (clk), .D (w6[2]), .Q (p[10]));
  DFFHQX2 \p_reg[9] (.CK (clk), .D (w6[1]), .Q (p[9]));
  DFFHQX2 \p_reg[8] (.CK (clk), .D (w6[0]), .Q (p[8]));
  DFFHQX2 \p_reg[7] (.CK (clk), .D (w5[3]), .Q (p[7]));
  DFFHQX2 \p_reg[6] (.CK (clk), .D (w5[2]), .Q (p[6]));
  DFFHQX2 \p_reg[5] (.CK (clk), .D (w5[1]), .Q (p[5]));
  DFFHQX2 \p_reg[4] (.CK (clk), .D (w5[0]), .Q (p[4]));
  DFFHQX2 \p_reg[3] (.CK (clk), .D (w[3]), .Q (p[3]));
  DFFHQX2 \p_reg[2] (.CK (clk), .D (w[2]), .Q (p[2]));
  DFFHQX2 \p_reg[1] (.CK (clk), .D (w[1]), .Q (p[1]));
  DFFHQX2 \p_reg[0] (.CK (clk), .D (w[0]), .Q (p[0]));
endmodule

